# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lanecv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lanecv.proto',
  package='acap',
  syntax='proto3',
  serialized_pb=_b('\n\x0clanecv.proto\x12\x04\x61\x63\x61p\"2\n\x0bLaneMessage\x12\x0e\n\x06offset\x18\x01 \x01(\x01\x12\x13\n\x0borientation\x18\x02 \x01(\x01\"<\n\x11LaneMessageSingle\x12\'\n\x0claneMessage1\x18\x01 \x01(\x0b\x32\x11.acap.LaneMessage\"e\n\x11LaneMessageDouble\x12\'\n\x0claneMessage1\x18\x01 \x01(\x0b\x32\x11.acap.LaneMessage\x12\'\n\x0claneMessage2\x18\x02 \x01(\x0b\x32\x11.acap.LaneMessageB!\n\nacap.modelB\x13LaneMessageProtocolb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LANEMESSAGE = _descriptor.Descriptor(
  name='LaneMessage',
  full_name='acap.LaneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='acap.LaneMessage.offset', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='acap.LaneMessage.orientation', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=72,
)


_LANEMESSAGESINGLE = _descriptor.Descriptor(
  name='LaneMessageSingle',
  full_name='acap.LaneMessageSingle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='laneMessage1', full_name='acap.LaneMessageSingle.laneMessage1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=134,
)


_LANEMESSAGEDOUBLE = _descriptor.Descriptor(
  name='LaneMessageDouble',
  full_name='acap.LaneMessageDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='laneMessage1', full_name='acap.LaneMessageDouble.laneMessage1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laneMessage2', full_name='acap.LaneMessageDouble.laneMessage2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=237,
)

_LANEMESSAGESINGLE.fields_by_name['laneMessage1'].message_type = _LANEMESSAGE
_LANEMESSAGEDOUBLE.fields_by_name['laneMessage1'].message_type = _LANEMESSAGE
_LANEMESSAGEDOUBLE.fields_by_name['laneMessage2'].message_type = _LANEMESSAGE
DESCRIPTOR.message_types_by_name['LaneMessage'] = _LANEMESSAGE
DESCRIPTOR.message_types_by_name['LaneMessageSingle'] = _LANEMESSAGESINGLE
DESCRIPTOR.message_types_by_name['LaneMessageDouble'] = _LANEMESSAGEDOUBLE

LaneMessage = _reflection.GeneratedProtocolMessageType('LaneMessage', (_message.Message,), dict(
  DESCRIPTOR = _LANEMESSAGE,
  __module__ = 'lanecv_pb2'
  # @@protoc_insertion_point(class_scope:acap.LaneMessage)
  ))
_sym_db.RegisterMessage(LaneMessage)

LaneMessageSingle = _reflection.GeneratedProtocolMessageType('LaneMessageSingle', (_message.Message,), dict(
  DESCRIPTOR = _LANEMESSAGESINGLE,
  __module__ = 'lanecv_pb2'
  # @@protoc_insertion_point(class_scope:acap.LaneMessageSingle)
  ))
_sym_db.RegisterMessage(LaneMessageSingle)

LaneMessageDouble = _reflection.GeneratedProtocolMessageType('LaneMessageDouble', (_message.Message,), dict(
  DESCRIPTOR = _LANEMESSAGEDOUBLE,
  __module__ = 'lanecv_pb2'
  # @@protoc_insertion_point(class_scope:acap.LaneMessageDouble)
  ))
_sym_db.RegisterMessage(LaneMessageDouble)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\nacap.modelB\023LaneMessageProtocol'))
# @@protoc_insertion_point(module_scope)
